server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://192.168.1.209:3306/mysmart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
#    myresource:
#      jdbcUrl: jdbc:mysql://192.168.1.209:3306/myresource?useUnicode=true&characterEncoding=UTF-8&useSSL=false #url
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.example.database.entity
configuration:
  map-underscore-to-camel-case: true


